#!/usr/bin/python3
#$ cat /usr/bin/jupyter-kernelspec

import re
import sys

from jupyter_client.kernelspecapp import KernelSpecApp

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        KernelSpecApp.launch_instance()
    )
